### ISSUE TITLE
Documents

### ISSUE THREAD

**Issue by coolpalani** [pradiptapks/OSP_Director_OpenDayLight#1]
Hello,

Can I get some sort for steps to deploy RedHat OpenStack with NFS using your repo

**Comment by pradiptapks** [comment]
The OpenDayLight template is in under testing. Please let me know if you are deploying for OpenDaylight

**Comment by coolpalani** [comment]
We have deployed RedHat OpenStack platform 11 and it's running as fine. OpenDaylight is becoming more popular and we are interested to test it out. 
I would appreciate if you are helping on this.
